# Generated by Django 2.0 on 2020-12-30 08:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_name', models.CharField(blank=True, default='', max_length=100, verbose_name='支払い項目')),
                ('payment_value', models.IntegerField(default=0, verbose_name='支払い額')),
            ],
        ),
    ]
