# Generated by Django 2.0 on 2020-12-31 05:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paymentchart', '0002_paymentitem_payment_data'),
    ]

    operations = [
        migrations.CreateModel(
            name='BankList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bank_code', models.CharField(blank=True, default='', max_length=100, verbose_name='銀行コード')),
                ('bank_name', models.CharField(blank=True, default='', max_length=100, verbose_name='銀行名')),
            ],
        ),
    ]
