# Generated by Django 2.0 on 2020-12-31 05:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paymentchart', '0003_banklist'),
    ]

    operations = [
        migrations.AlterField(
            model_name='banklist',
            name='bank_code',
            field=models.CharField(max_length=100, unique=True, verbose_name='銀行コード'),
        ),
    ]
