# Generated by Django 2.0 on 2020-12-31 05:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('paymentchart', '0004_auto_20201231_1431'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymentitem',
            name='bank',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='banks', to='paymentchart.BankList'),
        ),
    ]
